package Lesson3;

import java.util.*;
import java.lang.*;

public class Lesson3_GameNumbers {
    static Scanner input = new Scanner(System.in);
    public static void main(String[] args) {

        int resumeGame;
        System.out.println("Guess the number game\n");
        playGame();
        do {
            System.out.print("Do you want to continue? (1) - Yes; (2) - No: ");
            resumeGame = input.nextInt();
            if (resumeGame == 1){
                playGame();
            } else {
                System.out.println("Thanks for playing with us, goodbye!");
            }
        } while (resumeGame != 2);


    }
    static void playGame(){
        Random rand = new Random();
        int userAnswer;
        int hiddenNumber;
        int count;
        hiddenNumber = rand.nextInt(10);
        count = 3;
        System.out.println("The system guessed a number from 0 to 9, you have 3 attempts to guess it.");
        while (count > 0) {
            do {
                System.out.print("Enter your answer: ");
                userAnswer = input.nextInt();
            } while (userAnswer > 9 || userAnswer < 0);
            if (userAnswer == hiddenNumber) {
                System.out.println("Congratulations, you guessed it!");
                break;
            } else if (userAnswer > hiddenNumber) {
                System.out.println("Your number is greater than the one generated by the system.");
                count--;
            } else if (userAnswer < hiddenNumber) {
                System.out.println("Your number is lower than the one generated by the system.");
                count--;
            }
        }
        if (count == 0) {
            System.out.println("You have used all the attempts.");
        }
    }


}
